### ISSUE TITLE
clarification 

### ISSUE THREAD

**Issue by Alexander020304** [Bactrosaurus/bactromod#1]
how does this optimize the game in any way? it just provides utility to the user.

**Comment by ghost** [comment]
From what I can tell, this mod just removes/modify vanilla features and also adds useless features that are not necessary.
**Maybe @Bactrosaurus thought that removing the darkness effect might help with performance?**

**Comment by Bactrosaurus** [comment]
Well, optimization is of course a subjective matter. I personally know a bunch of people who would certainly profit from these features (especially those playing survival). A lower shield and lower fire texture e.g. gives the players more view, the same goes of course for the gamma multiplier, disabled darkness fog and pumpkin blur.
If one also looks at the screenshots I posted in the README file, it becomes very clear that every feature can be toggled on or off, depending on your needs. I will, however, remove the word "optimize" from the description as it may cause confusion regarding users who understand optimization just on a performance based level. And no @MrRagtime I don't think removing darkness fog significantly helps with performance and that is also not the reason why it is present in the mod. If you think features are unnecessary, I would recommend not using them.

**Comment by ghost** [comment]
To me, these features are pointless but I do believe there are people out there who would enjoy these features.
