### ISSUE TITLE
tridents with shields

### ISSUE THREAD

**Issue by Tikam10** [Bactrosaurus/bactromod#10]
hey yo could you make riptide tridents with a shield in your offhand not absolutely cover the entirety of your screen? This isnt a bug with the mod, im just asking because mojang refuses to lower the shield when using a riptide trident. Thanks! (also could you make that version for 1.20.1 also)

**Comment by Bactrosaurus** [comment]
Thats actually really bad... Thank's for bringing this issue to my attention. I will fix this when I have a bit more spare time

**Comment by Bactrosaurus** [comment]
I have implemented a quick fix by disabling the riptide-animation for a shield. Other items animation is not affected by this. New version will be released on Modrinth after some testing.

**Comment by Tikam10** [comment]
thanks so much, this means a lot to me, this mod saves lives
